package io.github.rehody.abplatform.model.audit;

public enum AuditAction {
    EXPERIMENT_CREATED,
    EXPERIMENT_UPDATED,
    EXPERIMENT_SUBMITTED_FOR_REVIEW,
    EXPERIMENT_APPROVED,
    EXPERIMENT_REJECTED,
    EXPERIMENT_STARTED,
    EXPERIMENT_PAUSED,
    EXPERIMENT_RESUMED,
    EXPERIMENT_COMPLETED,
    EXPERIMENT_ARCHIVED,
    EXPERIMENT_ROLLOUT_ADVANCED_MANUAL,
    EXPERIMENT_ROLLOUT_ROLLED_BACK_MANUAL,
    EXPERIMENT_ROLLOUT_ADVANCED_AUTO,
    EXPERIMENT_ROLLOUT_ROLLED_BACK_AUTO,
    EXPERIMENT_PAUSED_AUTO_AFTER_ROLLOUT_ROLLBACK,
    EXPERIMENT_METRIC_BINDINGS_UPDATED,
    EXPERIMENT_RISK_RESOLVED,
    METRIC_DEFINITION_CREATED,
    METRIC_DEFINITION_UPDATED,
    FEATURE_FLAG_CREATED,
    FEATURE_FLAG_UPDATED
}
